# Generated by Django 3.1.6 on 2021-02-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_owner', models.CharField(max_length=30)),
                ('post_content', models.CharField(max_length=1000)),
            ],
        ),
    ]
